sushiswap/sushiswap-interface

- src/components/swap/styleds.tsx
- src/constants/Fraction.ts
- src/constants/sushiAbis/saave.json
- src/pages/App.tsx
- src/pages/Saave/AXSushiBalancePanel.tsx
- src/pages/Saave/SaaveHeader.tsx
- src/pages/Saave/SushiInputPanel.tsx
- src/pages/Saave/index.tsx
- src/sushi-hooks/useAllowanceSaave.ts
- src/sushi-hooks/useApproveSaave.ts
- src/sushi-hooks/useContract.ts
- src/sushi-hooks/useSaave.ts
- src/sushi-hooks/useTokenBalance.ts
- src/utils/index.ts
Implements UI and web3 hooks for @Ro5s 's SAAVE (Sushi - xSUSHI - aXSUSHI) contract: https://twitter.com/r_ross_campbell/status/1367590232325906437?s=20
> Experimental saave contract

- src/components/Header/index.tsx
- src/pages/App.tsx
- src/pages/Tools/index.tsx
Adds a pattern for gracefully removing routes given a network switch
> Add mainnet routes

- src/constants/index.ts
+ Added a custom base to route pONT thru pWING.
> Added Custom Base for pONT to pWING

- src/components/LanguageSwitch/index.tsx
- src/components/Menu/index.tsx
- src/components/Settings/index.tsx
- src/components/StyledMenu/index.tsx
> fix styling issues of settings dropdown

- src/constants/index.ts
+ Adds custom base for PLAY -> DOUGH
> Add custom route for PLAY to DOUGH

- src/kashi/components/Layout.tsx
- src/kashi/pages/Markets/Borrow/Positions.tsx
- src/kashi/pages/Markets/Borrow/index.tsx
- src/kashi/pages/Markets/Lending/Positions.tsx
> Kashi polish

- src/components/CurrencyLogo/index.tsx
- src/hooks/useContract.ts
- src/hooks/useLPTokensState.ts
- src/hooks/useMigrateState.ts
- src/pages/App.tsx
- src/pages/MigrateV2/index.tsx
- src/pages/Pool/index.tsx
- src/theme/components.tsx
Updates to Migrate to function on both mainnet and bsc with necessary fallbacks if rpc nodes are unable to query
> Migrate Update

- src/components/AppBar.tsx
- src/pages/App.tsx
#71 This is one possible idea for how to conditionally render styles on the trading view. It abstracts the classList for the App Wrapper component and the Nav component into a piece of state, which it can conditionally update based on the path in the route. The two changes you requested (removing the padding on the chart, and removing the gradient border) consist of removing classes from the tailwind classList so this approach works.
The third thing you requested (updating the background colors) I didn't quite follow. Which background colors need to be updated? And how can you update them to three separate colors? sorry was a bit confused by that.
> [71] Custom Styles for Trading View Integration

- src/components/Liquidity/AdvancedLiquidityDetails.tsx
- src/components/Liquidity/AdvancedLiquidityDetailsDropdown.tsx
- src/components/Liquidity/LiquidityHeader.tsx
- src/components/Liquidity/LiquidityPrice.tsx
- src/components/Liquidity/RemoveLiquidityReceiveDetails.tsx
- src/components/PercentInput/index.tsx
- src/components/PercentInputPanel/index.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/RemoveLiquidity/index.tsx
RemoveLiquidity Page Restyling is finished.
> Restyle remove liquidity

- src/pages/Migrate/index.tsx
This PR belongs to the issue #89
> Style Improvements to Migration Page

- src/components/Liquidity/RemoveLiquidityReceiveDetails.tsx
- src/pages/RemoveLiquidity/index.tsx
This PR is related with #110 .
> fix: make remove liquidity mobile responsive

- src/components/WalletModal/index.tsx
- src/components/Web3Status/index.tsx
> fix: unable to disconnect on wrong network connection

- src/components/CurrencySelectPanel/index.tsx
- src/components/PositionCard/index.tsx
- src/pages/PoolFinder/index.tsx
- src/utils/shortenString.ts
This PR for issue #90 is summited again with latest canary rebase
> fix: restyle pool finder page

- src/components/PublicRoute.tsx
- src/components/WalletRoute.tsx
- src/index.tsx
- src/kashi/routes.tsx
- src/routes.tsx
refactor: remove KashiProvider from index.tsx and transform Kashi into a module
> Separate Kashi from the rest of the app

- src/pages/SushiBar/InfoCard.tsx
> Fixed typo in info card.

- src/components/AppBar.tsx
> change Disclosure to Popover in mobile AppBar menu

- src/state/swap/hooks.ts
Fixes Archer dynamic tip setting
> fix: archer dynamic tip setting

- locale/de.po
- locale/en.po
- locale/es-AR.po
- locale/es.po
- locale/fr.po
- locale/it.po
- locale/ja.po
- locale/ko.po
- locale/ro.po
- locale/ru.po
- locale/vi.po
- locale/zh-CN.po
- locale/zh-TW.po
- src/components/AccountDetails/Copy.tsx
- src/components/AccountDetails/Transaction.tsx
- src/components/AccountDetails/index.tsx
- src/components/ExternalLink/index.tsx
- src/components/ModalHeader/index.tsx
- src/components/QuestionHelper/index.tsx
- src/components/Settings/index.tsx
- src/components/TransactionSettings/index.tsx
- src/styles/index.css
- src/styles/variables.css
Refactor: Settings
Refactor: AccountDetails
Feat: Style scrollbar
> refactor: styled components to tailwind for settings

- public/manifest.json
- vercel.json
> Fix Safe app manifest

- locale/de.po
- locale/en.po
- locale/es-AR.po
- locale/es.po
- locale/fr.po
- locale/it.po
- locale/ja.po
- locale/ko.po
- locale/ro.po
- locale/ru.po
- locale/vi.po
- locale/zh-CN.po
- locale/zh-TW.po
- src/features/meowshi/HeaderToggle.tsx
- src/hooks/useMeowshiPerXSushi.ts
- src/hooks/useXSushiPerSushi.ts
- src/pages/bar/index.tsx
- src/pages/tools/meowshi.tsx
> Meowshi Fixes

- locale/de.po
- locale/en.po
- locale/es-AR.po
- locale/es.po
- locale/fr.po
- locale/it.po
- locale/ja.po
- locale/ko.po
- locale/ro.po
- locale/ru.po
- locale/vi.po
- locale/zh-CN.po
- locale/zh-TW.po
- src/features/limit-order/PriceRatio.tsx
- src/pages/exchange/open-order/index.tsx
fix: ratio switcher now works with rate selected in input
fix: show alert if user has not approved master contract but has orders
> Limit order enhancements

- package.json
- yarn.lock
Hi SushiTeam,
Update the Keystone connector version to latest one :)
> feat: update keystone connector version

- package.json
- src/components/AccountDetails/index.tsx
- src/components/Web3Status/index.tsx
- src/connectors/index.ts
- src/constants/index.ts
- yarn.lock
Hi Sushi Team,
Just upgrade the connector version and async load the connector :)
> feat: use async load for keystone connector

- package.json
- yarn.lock
There have been big perf improvements in the latest WC versions, would greatly improve Sushi's mobile experience
announcement here: https://twitter.com/WalletConnect/status/1426226788515078144?s=20
> bump walletconnect 1.6.0 - huge performance improvement

- src/components/AccountDetails/index.tsx
- src/components/Web3Status/index.tsx
- src/connectors/index.ts
- src/constants/index.ts
- src/modals/WalletModal/Standalone.tsx
- src/modals/WalletModal/index.tsx
> Lazy Load Connectors

- src/state/swap/hooks.ts
closes #294
Added logic to ensure a token will always be selected regardless of the params
> feat: default to eth/sushi swap state

- package.json
- src/components/Popover/index.tsx
- src/modals/SearchModal/ManageLists.tsx
Closes #291
Popovers behave and appear the same as before. Added an opaque background to the Manage Token List popover to make the content more visible
> chore: cleanup popovers

- package.json
- src/components/Logo/index.tsx
- src/features/onsen/FarmList.tsx
- src/features/onsen/FarmMenu.tsx
- src/features/onsen/hooks.ts
- src/styles/index.css
- yarn.lock
Demo + explanation: https://www.youtube.com/watch?v=GK2FrUQqnE0 (processing...)
- Optimistic UI for 'Your Farms' tab
- Infinite scroll loading for farms list
- Various bug fixes
Idea origin: https://github.com/sushiswap/sushiswap-interface/discussions/284
> Feat: optimistic UI farm tab + infinite scroll

- src/state/wallet/hooks.ts
Video walkthrough: https://www.youtube.com/watch?v=n1qhN486rvA
Problem: swap page modal feels delayed as it pops up and typing
Solution: a pesky JSON.stringify slowing the world down
> Improving UI renders on swap page

- package.json
- src/state/lists/wrappedTokenInfo.ts
- src/state/wallet/hooks.test.ts
- src/state/wallet/hooks.ts
- src/state/wallet/types.ts
- yarn.lock
Follow up to: https://github.com/sushiswap/sushiswap-interface/pull/339
> fix: swap stringify with custom serializer to speed up renders

- src/features/onsen/CurrencyInputPanel.tsx
- src/features/onsen/FarmListItem.tsx
- src/features/onsen/FarmListItemDetails.tsx
- src/features/onsen/InformationDisclosure.tsx
- src/features/onsen/InvestmentDetails.tsx
- src/features/onsen/KashiDeposit.tsx
- src/features/onsen/KashiWithdraw.tsx
- src/features/onsen/ManageBar.tsx
- src/features/onsen/ManageKashiPair.tsx
- src/features/onsen/ManageSwapPair.tsx
- src/features/onsen/PoolAddLiquidity.tsx
- src/features/onsen/PoolRemoveLiquidity.tsx
- src/features/onsen/usePendingReward.ts
- src/pages/farm/index.tsx
- src/state/burn/hooks.ts
- src/state/wallet/hooks.ts
extend farm details panel according to new designs
add kashi & exchange integrations
> Update farm details panel

- src/features/farm/CurrencyInputPanel.tsx
- src/features/farm/FarmListItem.tsx
- src/features/farm/FarmListItemDetails.tsx
- src/features/farm/InformationDisclosure.tsx
- src/features/farm/InvestmentDetails.tsx
- src/features/farm/KashiDeposit.tsx
- src/features/farm/KashiWithdraw.tsx
- src/features/farm/ManageBar.tsx
- src/features/farm/ManageKashiPair.tsx
- src/features/farm/ManageSwapPair.tsx
- src/features/farm/PoolAddLiquidity.tsx
- src/features/farm/PoolRemoveLiquidity.tsx
- src/pages/farm/index.tsx
- src/state/burn/hooks.ts
- src/state/wallet/hooks.ts
> master: update farm details panel

- src/features/farm/FarmListItemDetails.tsx
- src/features/farm/InformationDisclosure.tsx
- src/features/farm/InvestmentDetails.tsx
- src/features/farm/ManageBar.tsx
- src/features/farm/PoolRemoveLiquidity.tsx
> master: mobile styling for farm details

- package.json
- yarn.lock
https://github.com/faisalman/ua-parser-js/issues/536
> fix: add resolution for dep with vuln

- src/components/Header/DesktopNav.tsx
- src/components/Header/MobileNav.tsx
- src/components/Header/More.tsx
- src/components/Modal/HeadlessUIModal.tsx
- src/components/Web3Status/index.tsx
- src/features/trident/balances/AssetBalances/useLPTableConfig.tsx
- src/features/trident/balances/AssetBalances/useTableConfig.tsx
- src/features/trident/balances/HeaderDropdown.tsx
- src/layouts/Default/index.tsx
- src/modals/SearchModal/CurrencySearch.tsx
- src/modals/SearchModal/CurrencySearchModal.tsx
feat: hide balance in header on mobile because of overflow
fix: always show balances in mobile nav
fix: more icon wasnt showing on mobile
fix: headlesuimodal had padding and height issues on mobile
fix: balances tables had a too large minwidth
fix: default layout had redundant bottom padding
fix: currencyselectmodal had incorrect overflow
> Mobile fixes

- src/components/Switch/index.tsx
- src/components/Web3Network/index.tsx
- src/features/trident/DepositSubmittedModalContent.tsx
- src/features/trident/WithdrawalSubmittedModalContent.tsx
- src/features/trident/context/hooks/useSwapAssetPanelInputs.tsx
- src/features/trident/create/classic/SelectAssetsWidget.tsx
- src/features/trident/swap/DerivedTradeContext.ts
- src/features/trident/swap/RecipientPanel.tsx
- src/features/trident/swap/SwapAssetPanel.tsx
- src/features/trident/swap/SwapButton.tsx
- src/features/trident/swap/SwapRate.tsx
- src/features/trident/swap/SwapReviewModal.tsx
- src/features/trident/swap/SwapSubmittedModalContent.tsx
- src/features/trident/swap/WrapButton.tsx
- src/features/trident/swap/_useSwapPage.ts
- src/features/trident/swap/swapSlice.ts
- src/hooks/useBentoRebases.ts
- src/hooks/useBestTridentTrade.ts
- src/hooks/useTransactionStatus.ts
- src/hooks/useUSDCPrice.ts
- src/modals/SearchModal/ImportToken.tsx
- src/pages/trident/swap/index.tsx
- src/state/reducer.ts
feat: reduce renders of swap page significantly
refactor: add reducer for trident swap 
refactor: remove every recoil value for trident swap
feat: transaction status by txhash hook
refactor: add a derived trade context to avoid calculating best price multiple times
fix: importToken dialog padding
feat: reduce amount of renders happening in useBestTridentTrade
refactor: remove context provider for swap asset panel inputs for performance reasons
fix: remove teal color from switch
> Trident Swap Optimizations

- package.json
- src/components/Settings/index.tsx
- src/components/Switch/index.tsx
- src/components/TransactionSettings/index.tsx
- src/features/miso/AuctionCard/index.tsx
- src/features/miso/AuctionCommitter/index.tsx
- src/features/miso/CommitReviewModal.tsx
- src/features/miso/context/hooks/useAuction.ts
- yarn.lock
style: transaction settings design
fix: miso error with undefined lpTokenAddress
> style: transaction settings design

- src/modals/SearchModal/CurrencyList.tsx
- test/e2e/pages/shared/CurrencySelectComponent.ts
- test/e2e/pages/swap/SwapPage.ts
Added token selector to new currency list
> fix: currency select refactor

- src/components/Web3Status/index.tsx
> feat: add ens avatar support

- src/components/Footer/index.tsx
- src/components/Header/More.tsx
- src/features/miso/AuctionAdminForm/AuctionAdminFormWhitelistSection/index.tsx
- src/features/miso/AuctionAdminForm/index.tsx
- src/pages/vesting/index.tsx
> chore: rename Github to GitHub

- babel.config.js
- package.json
- yarn.lock
> fix: babel config

- src/components/AssetInput/index.tsx
- src/components/LanguageSwitch/index.tsx
- src/features/onsen/FarmList.tsx
- src/features/onsen/FarmMenu.tsx
- src/features/onsen/hooks.ts
- src/hooks/useSortableData.ts
- src/pages/farm/index.tsx
style(LanguageSwitch): new style plus close bug
fix(Onsen): show reward modal if you have balance
fix(Onsen): close filter menu on click
fix(Onsen): table pool sort
> fix(AssetInput): overflow of symbol

- src/components/Web3Status/index.tsx
> svg, not png

- src/features/user/MultichainExploitAlertModal.tsx
- src/pages/_app.tsx
API: https://gist.github.com/zhaojun-sh/8e187fd9563805850f56348164ab1984
A user safety alert to revoke approvals for at risk assets on Multichain.
> feat: multichain exploit alert

- src/config/tridentMigration.ts
- src/constants/abis/eip-2612.json
- src/constants/abis/trident-migration.json
- src/features/onsen/PoolAddLiquidity.tsx
- src/features/onsen/PoolRemoveLiquidity.tsx
- src/features/trident/TridentApproveGate.tsx
- src/features/trident/actions.ts
- src/features/trident/add/useAddLiquidityExecute.ts
- src/features/trident/create/useCreatePoolExecute.ts
- src/features/trident/migrate/AvailableToMigrate.tsx
- src/features/trident/migrate/MigrationTransactionModal.tsx
- src/features/trident/migrate/SelectPoolsAndConfirm.tsx
- src/features/trident/migrate/context/migrateSlice.ts
- src/features/trident/migrate/context/tridentMigrateAction.ts
- src/features/trident/migrate/context/useExecuteTridentMigration.ts
- src/features/trident/remove/useRemoveLiquidityExecute.ts
- src/features/trident/remove/useRemoveLiquiditySingleExecute.ts
- src/functions/contract.ts
- src/hooks/useBentoMasterApproveCallback.ts
- src/hooks/useContract.ts
- src/hooks/useERC20Permit.ts
- src/hooks/useKashiApproveCallback.ts
- src/hooks/useSwapCallback.ts
- src/pages/legacy/add/[[...tokens]].tsx
- src/pages/legacy/migrate/index.tsx
- src/pages/legacy/remove/[[...tokens]].tsx
- src/pages/legacy/swap/[[...tokens]].tsx
- src/pages/trident/migrate/confirm/index.tsx
- src/services/web3/WalletError.ts
Adding batch approve+migrate actions to migration page.
Next PR: make proper estimations on min recieved.
> feat: trident migration enabled

- src/components/AssetInput/index.tsx
- src/features/trident/balances/ActionsModal/WithdrawView.tsx
- src/features/trident/balances/AssetBalances/AssetBalances.tsx
- src/features/trident/balances/AssetBalances/index.tsx
- src/features/trident/balances/AssetBalances/useTableConfig.tsx
- src/features/trident/balances/BalancesSum.tsx
- src/features/trident/migrate/context/useV2PairsWithLiquidity.ts
- src/hooks/useBentoBox.ts
- src/hooks/useUSDCPrice.ts
- src/pages/trident/balances/index.tsx
- src/state/wallet/hooks.ts
- src/styles/index.css
style(Balances): add skeletons for tables
feat(Pricing): add loading indicators for fetchin usdc price
fix(BentoBox): when withdrawing with max use shares instead of amounts
> style(Balances): have a better overview for balances

- src/components/AssetInput/index.tsx
- src/components/AssetSelect/index.tsx
- src/features/trident/balances/ActionsModal/DepositView.tsx
- src/features/trident/balances/ActionsModal/WithdrawView.tsx
- src/features/trident/balances/AssetBalances/AssetBalances.tsx
- src/features/trident/balances/AssetBalances/index.tsx
- src/features/trident/balances/BalancesSum.tsx
- src/hooks/useBentoBox.ts
- src/hooks/useBentoOrWalletBalance.ts
- src/state/bentobox/hooks.ts
- src/state/inari/strategies/useStakeSushiToBentoStrategy.ts
- src/state/inari/strategies/useStakeSushiToCreamToBentoStrategy.ts
fix(Balances): withdraw when using max button
feat(useBentoBalance): pass loading state down
> fix(Balances): infinite loader if no balances

- src/components/Header/Desktop.tsx
- src/components/Header/Mobile.tsx
- src/components/Settings/index.tsx
- src/hooks/useIsCoinbaseWallet.tsx
- src/hooks/useWalletSupportsOpenMev.tsx
- src/pages/legacy/swap/[[...tokens]].tsx
feat: disable OpenMev for coinbase wallets. 
feat(useIsCoinbaseWallet) clean up duplicate isCBWallet checks
feat(useWalletSupportsOpenMev) Add hook to abstract supported wallets while being flexible to add more if needed later.
> feat: disable openmev for cb wallet

- src/config/tridentMigration.ts
- src/constants/abis/trident-migration.json
- src/features/trident/migrate/SelectPoolsAndConfirm.tsx
- src/features/trident/migrate/SlippageWidget.tsx
- src/features/trident/migrate/context/errorPopups.ts
- src/features/trident/migrate/context/tridentMigrateAction.ts
- src/features/trident/migrate/context/useExecuteTridentMigration.ts
- src/hooks/useTotalSupply.ts
- src/services/web3/WalletError.ts
- src/state/index.ts
> feat: calculating slippage for trident migration

- src/state/slippage/slippageSlice.ts
Without create selector, Redux does not properly memoize and thinks it should keep dispatching a new slippage Percent class.
> fix: create selector to fix infinite loop

- src/features/miso/AuctionClaimer/index.tsx
- src/features/miso/AuctionCommitter/index.tsx
- src/features/miso/AuctionDocuments/index.tsx
- src/features/miso/AuctionFinalizeModal.tsx
- src/features/miso/AuctionHeader/index.tsx
- src/features/miso/AuctionStats/index.tsx
- src/features/miso/AuctionTabs/index.tsx
- src/features/miso/context/AuctionContext.tsx
- src/features/miso/context/hooks/useAuction.ts
- src/features/miso/context/hooks/useAuctionInfo.ts
- src/pages/miso/[auction]/index.tsx
feat(Miso): auction context for easy accessing of auction
> feat(Miso): loading state with 404 if not found

- src/features/miso/context/hooks/useAuction.ts
- src/features/miso/context/hooks/useAuctionCreate.ts
- src/features/miso/context/hooks/useAuctionInfo.ts
- src/pages/miso/[auction]/index.tsx
- src/pages/miso/auction/index.tsx
- src/pages/miso/index.tsx
- src/pages/miso/launcher/index.tsx
- src/pages/miso/token/index.tsx
> fix(Miso): admin button not showing

- src/features/transactions/Transactions.tsx
- src/features/trident/pool/PoolStatsChart.tsx
- src/features/trident/remove/ClassicSingleAside.tsx
- src/features/trident/remove/ClassicSingleMode.tsx
- src/features/trident/remove/ClassicStandardAside.tsx
- src/features/trident/remove/ClassicStandardMode.tsx
- src/features/trident/swap/SwapAssetPanel.tsx
- src/hooks/useSwapCallback.ts
- src/pages/trident/swap/index.tsx
- src/services/graph/fetchers/pools.ts
- src/services/graph/hooks/pools.ts
- src/services/graph/hooks/transactions/trident.ts
- src/services/graph/queries/pools.ts
1. Transactions - fetching, pricing
2. Swapping - when not in expert mode, recipient was undefined
3. Pool graphs - indexing, fetching
> fix: misc trident bugs

- next.config.js
- package.json
- yarn.lock
use critters to inline critical css
> feat(nextjs): inline critical css improvement

- next.config.js
- package.json
- yarn.lock
Reverts sushiswap/sushiswap-interface#654
> Revert "feat(nextjs): inline critical css improvement"

- src/features/transactions/Transactions.tsx
- src/features/transactions/useTableConfig.tsx
- src/services/graph/hooks/transactions/trident.ts
> fix: trident pool transaction date sorting

- src/features/trident/pool/Header.tsx
feat(Trident): create link to explorer for pool
feat(Trident): allow copying pool address
> feat(Trident): create link to explorer for pool

- src/components/Header/Mobile.tsx
- src/pages/analytics/xsushi.tsx
fix: clarify xSushi description (https://github.com/sushiswap/sushiswap-interface/issues/598)
> fix: connect wallet not showing up on mobile

- src/features/legacy/limit-order/MyOrders.tsx
- src/features/legacy/limit-order/OrderTableToggle.tsx
- src/features/legacy/limit-order/useOpenOrdersTableConfig.tsx
Fixes: https://github.com/sushiswap/sushiswap-interface/issues/594
> fix: hide expired orders from `/limit-order/open`

- src/hooks/useSwapCallback.ts
This PR fixes sending invalid TXs for those Wallet providers that add the `Ethereum Signed Message` string while using `eth_sign` and warns the user to use a different Wallet provider or to disable SushiGuard feature.
> fix(sushiguard): added additional check to avoid sending invalid txs if wallet is not supported

- src/features/account/AssetBalances/liquidityPositions/hooks.ts
- src/features/analytics/pools/PairList.tsx
- src/features/analytics/pools/useTableConfig.tsx
- src/functions/apy.ts
> fix: getApy days

- package.json
- src/config/token-lists.ts
- src/state/lists/hooks.ts
- yarn.lock
This reverts commit 346ef77d3353ec730accf9ce080b122d1548ec76.
> Revert "feat: remove default list dependency and load async"

- next.config.js
- src/components/Header/useMenu.tsx
- src/components/Web3Network/index.tsx
- src/features/portfolio/ActionsModal/ActionView.tsx
- src/features/trade/HeaderNew.tsx
- src/features/trident/pool/ClassicLinkButtons.tsx
- src/features/trident/useCurrenciesFromURL.ts
- src/pages/legacy/swap/index.tsx
- src/pages/swap/index.tsx
- src/pages/trident/swap/index.tsx
fixes https://github.com/sushiswap/sushiswap-interface/issues/779
> feat(Swap): add facade page

- src/features/analytics/pools/getAnalyticsPairs.ts
- src/services/graph/fetchers/pager.ts
Reverts sushiswap/sushiswap-interface#834
> chore: Revert "Feature/pager"

- src/pages/analytics/pools/[id].tsx
Posted an issue related to this fix found here: https://github.com/sushiswap/sushiswap-interface/issues/867
> fix: Analytics Pool Rate Ticker
